/**
 * GitHub operations helper
 * Provides utilities for GitHub operations like creating PRs
 */

import { execSync } from 'child_process';
import { config } from '../config.js';
import * as logger from './logger.js';
import { pushChanges } from './git-helper.js';

/**
 * Create a pull request on GitHub
 */
export async function createPullRequest(
  workflowId: number,
  branchName: string,
  workflowType: string,
  workingDir: string,
  summary: string
): Promise<{ success: boolean; prUrl?: string; error?: string }> {
  try {
    // Check if GitHub is configured
    if (!config.github.token || !config.github.owner || !config.github.repo) {
      logger.warn('GitHub not configured - skipping PR creation');
      return {
        success: false,
        error: 'GitHub not configured (missing GITHUB_TOKEN, GITHUB_OWNER, or GITHUB_REPO)',
      };
    }

    logger.info('Creating pull request', { branchName, workflowType });

    // Push branch to remote
    const pushResult = await pushChanges(branchName, workingDir);
    if (!pushResult.success) {
      throw new Error(`Failed to push branch: ${pushResult.error}`);
    }

    // Create PR title and body
    const prTitle = `[Workflow ${workflowId}] ${workflowType}: Auto-generated changes`;
    const prBody = `## Workflow Summary

${summary}

---

**Workflow ID:** ${workflowId}
**Branch:** \`${branchName}\`
**Type:** ${workflowType}

🤖 This pull request was automatically generated by AIDeveloper.

### Review Checklist
- [ ] Code changes are correct and follow best practices
- [ ] Tests pass
- [ ] No security vulnerabilities introduced
- [ ] Documentation is updated if needed
`;

    // Use GitHub CLI to create PR
    logger.info('Creating PR via GitHub CLI');
    const prCommand = `gh pr create --title "${prTitle}" --body "${prBody.replace(/"/g, '\\"')}" --base ${config.git.defaultBranch} --head ${branchName}`;

    const prUrl = execSync(prCommand, {
      cwd: workingDir,
      encoding: 'utf-8',
      env: {
        ...process.env,
        GH_TOKEN: config.github.token,
      },
    }).trim();

    logger.info('Pull request created', { prUrl, branchName });

    return {
      success: true,
      prUrl,
    };
  } catch (error) {
    logger.error('Failed to create pull request', error as Error);
    return {
      success: false,
      error: (error as Error).message,
    };
  }
}

/**
 * Check if GitHub CLI is installed
 */
export function isGitHubCLIInstalled(): boolean {
  try {
    execSync('gh --version', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Add a comment to a specific commit on GitHub
 * This helps reviewers understand what each workflow stage did
 */
export async function addCommitComment(
  commitSha: string,
  comment: string,
  workingDir: string
): Promise<{ success: boolean; error?: string }> {
  try {
    // Check if GitHub is configured
    if (!config.github.token || !config.github.owner || !config.github.repo) {
      logger.debug('GitHub not configured - skipping commit comment');
      return {
        success: false,
        error: 'GitHub not configured',
      };
    }

    logger.info('Adding commit comment', { commitSha: commitSha.substring(0, 7) });

    // Use GitHub CLI API to create commit comment
    const apiCommand = `gh api repos/${config.github.owner}/${config.github.repo}/commits/${commitSha}/comments -f body="${comment.replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;

    execSync(apiCommand, {
      cwd: workingDir,
      encoding: 'utf-8',
      env: {
        ...process.env,
        GH_TOKEN: config.github.token,
      },
    });

    logger.info('Commit comment added successfully', { commitSha: commitSha.substring(0, 7) });

    return {
      success: true,
    };
  } catch (error) {
    logger.error('Failed to add commit comment', error as Error);
    return {
      success: false,
      error: (error as Error).message,
    };
  }
}

/**
 * Create workflow stage comment for GitHub commit
 * Matches format shown in workflow viewer for consistency
 */
export function formatWorkflowStageComment(
  workflowId: number,
  agentType: string,
  status: 'completed' | 'failed',
  summary: string,
  duration?: number,
  artifactsCount?: number
): string {
  const statusEmoji = status === 'completed' ? '✅' : '❌';
  const durationText = duration ? `\n**Duration:** ${(duration / 1000).toFixed(2)}s` : '';
  const artifactsText = artifactsCount ? `\n**Artifacts Created:** ${artifactsCount}` : '';

  return `## ${statusEmoji} Workflow Stage: ${agentType}

**Workflow ID:** #${workflowId}
**Status:** ${status.toUpperCase()}${durationText}${artifactsText}

### Summary

${summary}

---
*This comment was automatically generated to help reviewers understand the workflow execution. View full details at http://localhost:3000/workflows/${workflowId}*`;
}

/**
 * Add workflow stage comment to the latest commit
 * Gets the latest commit SHA and adds a formatted comment
 */
export async function addWorkflowStageComment(
  workflowId: number,
  agentType: string,
  status: 'completed' | 'failed',
  summary: string,
  workingDir: string,
  duration?: number,
  artifactsCount?: number
): Promise<{ success: boolean; error?: string }> {
  try {
    // Get latest commit SHA
    const commitSha = execSync('git rev-parse HEAD', {
      cwd: workingDir,
      encoding: 'utf-8',
    }).trim();

    // Format comment
    const comment = formatWorkflowStageComment(
      workflowId,
      agentType,
      status,
      summary,
      duration,
      artifactsCount
    );

    // Add comment to commit
    return await addCommitComment(commitSha, comment, workingDir);
  } catch (error) {
    logger.error('Failed to add workflow stage comment', error as Error);
    return {
      success: false,
      error: (error as Error).message,
    };
  }
}
