/**
 * GitHub operations helper
 * Provides utilities for GitHub operations like creating PRs
 */

import { execSync } from 'child_process';
import { config } from '../config.js';
import * as logger from './logger.js';
import { pushChanges } from './git-helper.js';

/**
 * Create a pull request on GitHub
 */
export async function createPullRequest(
  workflowId: number,
  branchName: string,
  workflowType: string,
  workingDir: string,
  summary: string
): Promise<{ success: boolean; prUrl?: string; error?: string }> {
  try {
    // Check if GitHub is configured
    if (!config.github.token || !config.github.owner || !config.github.repo) {
      logger.warn('GitHub not configured - skipping PR creation');
      return {
        success: false,
        error: 'GitHub not configured (missing GITHUB_TOKEN, GITHUB_OWNER, or GITHUB_REPO)',
      };
    }

    logger.info('Creating pull request', { branchName, workflowType });

    // Push branch to remote
    const pushResult = await pushChanges(branchName, workingDir);
    if (!pushResult.success) {
      throw new Error(`Failed to push branch: ${pushResult.error}`);
    }

    // Create PR title and body
    const prTitle = `[Workflow ${workflowId}] ${workflowType}: Auto-generated changes`;
    const prBody = `## Workflow Summary

${summary}

---

**Workflow ID:** ${workflowId}
**Branch:** \`${branchName}\`
**Type:** ${workflowType}

🤖 This pull request was automatically generated by AIDeveloper.

### Review Checklist
- [ ] Code changes are correct and follow best practices
- [ ] Tests pass
- [ ] No security vulnerabilities introduced
- [ ] Documentation is updated if needed
`;

    // Use GitHub CLI to create PR
    logger.info('Creating PR via GitHub CLI');
    const prCommand = `gh pr create --title "${prTitle}" --body "${prBody.replace(/"/g, '\\"')}" --base ${config.git.defaultBranch} --head ${branchName}`;

    const prUrl = execSync(prCommand, {
      cwd: workingDir,
      encoding: 'utf-8',
      env: {
        ...process.env,
        GH_TOKEN: config.github.token,
      },
    }).trim();

    logger.info('Pull request created', { prUrl, branchName });

    return {
      success: true,
      prUrl,
    };
  } catch (error) {
    logger.error('Failed to create pull request', error as Error);
    return {
      success: false,
      error: (error as Error).message,
    };
  }
}

/**
 * Check if GitHub CLI is installed
 */
export function isGitHubCLIInstalled(): boolean {
  try {
    execSync('gh --version', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}
